all:
  hosts:
    localhost:
  vars:
    ansible_connection: local

  children:
    remote:
      hosts:
        localhost:

    linux:
      hosts:
        localhost:
      vars:
        hostname: local-control
        hosts:
          dynamic:
            hostname: true
          static:
            - 127.0.0.1 me

    performance:
      hosts:
        localhost:
      vars:
        performance:
          result_path: ~/.seed/performance
