all:
  hosts:
    localhost:
  vars:
    ansible_connection: local

  children:
    remote:
      hosts:
        localhost:

    linux:
      hosts:
        localhost:
      vars:
        hostname: local-control
        hosts:
          dynamic:
            hostname: true
          static:
            - 127.0.0.1 me
        apt:
          sources:
            # check: true
            # sed: s@http://.*debian.org@http://mirrors.tuna.tsinghua.edu.cn@g
            cp:
              - dest: /etc/apt/sources.list
                backup: true
                content: |
                  deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free
                  deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free
                  deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free
                  deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free
              - dest: /etc/apt/sources.list
                backup: true
                src: "{{ inventory_dir }}/../apt/sources.list"
          packages:
            # check: true
            list:
              - name: rsync
                state: present
              - name:
                  - ntpdate
                  - chrony
                state: present
        yum:
          sources:
            check: false
            # sed: 
            #   expression: 
            #     mirrorlist: s|^mirrorlist=|#mirrorlist=|g
            #     baseurl: s|^# baseurl=https://repo.almalinux.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g
            #   file: /etc/yum.repos.d/almalinux-*.repo
            cp:
              - dest: /etc/yum.repos.d/almalinux.repo
                backup: true
                content: |
                  # almalinux.repo
              - dest: /etc/yum.repos.d/almalinux.repo
                backup: true
                src: "{{ inventory_dir }}/../yum/almalinux.repo"
          packages:
            # check: true
            list:
              - name: rsync
                state: present
              - name:
                  - ntpdate
                  - chrony
                state: present
        pip:
          mirror: https://pypi.tuna.tsinghua.edu.cn/simple
        networkd:
          eth0:
            - Match:
              - Name: "eth0"
            - Network:
              - Address: "172.19.73.184/20"
              - Gateway: "172.19.73.1"
        netplan:
          version: 2
          ethernets:
            eth0:
              addresses:
                - 172.19.73.184/20
              gateway4: 172.19.73.1
              nameservers:
                addresses:
                - 114.114.114.114
                search: []
        nmcli:
          state: present
          type: ethernet
          conn_name: eth0
          ifname: eth0
          ip4: 172.19.73.184/20
          gw4: 1172.19.73.1
        ufw:
          allow_interface_in: eth0
        firewalld:
          trusted_interface: 
            - eth0
          public_service: 
            - mountd
            - nfs
        chronyd:
          # conf:
          #   lineinfile:
          #     - regexp: '^pool'
          #       line: pool pool.ntp.org iburst maxsources 3
          #   copy:
          #     - src: "{{ inventory_dir }}/../chronyd/chronyd.conf"
        ntpd:
          # conf:
          #   lineinfile:
          #     - regexp: '^server 0'
          #       line: server 0.rhel.pool.ntp.org iburst
          #   copy:
          #     - src: "{{ inventory_dir }}/../ntpd/ntp.conf"
        timesyncd:
          # conf:
          #   lineinfile:
          #     - regexp: '^server 0'
          #       line: server 0.rhel.pool.ntp.org iburst
          #   copy:
          #     - src: "{{ inventory_dir }}/../timesyncd/timesyncd.conf"
    linux-master:
      hosts:
        localhost:
      vars:
        performance:
          result_path: ~/.seed/performance
    
    nfs-server:
      hosts:
        localhost:
      vars:
        nfs:
          test:
            point_type: 'nfs4'
            point_opts: 'rw,sync'
            point_nfs: "127.0.0.1:/"
            mount_dir: "/mnt/test-nfs-share"
            mount_permission: '0777'
          exports:
            - dir: '/eplatform-data'
              conf: '*(fsid=0,rw,no_root_squash,no_subtree_check,insecure)' 

    docker:
      hosts:
        localhost:

    docker-manager:
      hosts:
        localhost:

    docker-worker:
      hosts:
        # localhost:
