all:
  hosts:
    localhost:
  vars:
    ansible_connection: local

  children:
    remote:
      hosts:
        localhost:

    linux:
      hosts:
        localhost:

    performance:
      hosts:
        localhost:
      vars:
        performance:
          result_path: ~/.seed/performance
